[package]
name = "sixtyfps-rendering-backend-qt"
version = "0.0.1"
authors = ["Sixty FPS <info@sixtyfps.io>"]
edition = "2018"
license = "GPL-3.0-only"
description = "Qt rendering backend for SixtyFPS"
repository = "https://github.com/sixtyfpsui/sixtyfps"
homepage = "https://sixtyfps.io"

[features]
rtti = ["sixtyfps-corelib/rtti"]
default = ["rtti"]

[lib]
path = "lib.rs"

[dependencies]
cpp = "0.5.5"
const-field-offset = { version = "0.1", path = "../../../helper_crates/const-field-offset" }
vtable = { version = "0.1", path = "../../../helper_crates/vtable" }
sixtyfps-corelib-macros = { version = "=0.0.1", path = "../../corelib_macros" }
sixtyfps-corelib = { version="=0.0.1", path = "../../corelib" }
# FIXME: obviously, we do not want to depends on another backend
sixtyfps-rendering-backend-gl = { version="=0.0.1", path = "../gl" }
euclid = "0.22.1"
# Pin to work around regression in aho-corasick: https://github.com/BurntSushi/aho-corasick/issues/64
aho-corasick = "=0.7.4"
pin-weak = "1"

[build-dependencies]
cpp_build = "0.5.5"




